### KK-Pedia-2

GET https://script.google.com/macros/s/AKfycbzvjpiMT5DFMdEQXbFoeICOPJY6Q3Qhk6psRgMiKjiFEhovUDY/exec HTTP/1.1

### KK-Pedia-2

POST https://script.google.com/macros/s/AKfycbzvjpiMT5DFMdEQXbFoeICOPJY6Q3Qhk6psRgMiKjiFEhovUDY/exec HTTP/1.1

### KK-Pedia-3.v1: JSON

POST https://script.google.com/macros/s/AKfycbwtHU7yTNFy7-Nya7cyIyLuVa8uQk_Pz-hwDJizd1E9nDuA-mw/exec HTTP/1.1
content-type: application/json

{
    "action": "listRecentStory",
    "domain": "kanchanapisek.or.th"
}

###KK-Pedia-3.v2,3: URL encoded

POST https://script.google.com/macros/s/AKfycbwtHU7yTNFy7-Nya7cyIyLuVa8uQk_Pz-hwDJizd1E9nDuA-mw/exec HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache

action=listRecentStory&domain=kanchanapisek.or.th

###